### ISSUE TITLE
Python: Can't Open File

### ISSUE THREAD

**Issue by TuRDMaN** [a1ex4/ownfoil#5]
I just updated to the latest version. After starting the container, it stops right away. These are the only 3 lines in my log:

```
USERNAME and PASSWORD environment variables not set, skipping authentification setup.
Starting ownfoil
python: can't open file '/app/ownfoil.py': [Errno 2] No such file or directory
```

I wiped out all images/volumes related to ownfoil and tried again, but the same thing happened again.

Here is my docker-compose:

```
ownfoil: 
    container_name: ownfoil
    image: a1ex4/ownfoil
    restart: unless-stopped
    environment:
      - ROOT_DIR=/games
    network_mode: bridge
    ports:
      - 9080:80/tcp
    volumes:
      - '/mnt/Roms/Switch:/games'
```
